src/main/java/a/b/c/domain/user/UserEntity.java
package a.b.c.domain.user;

import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import a.b.c.domain.code.GenderCd;
import a.b.c.infrastructure.code.CodeUtils;
import a.b.c.infrastructure.data.jpa.BaseEntityListener;

@Entity
@Table(name = "USER_ENTITY")
@EntityListeners(BaseEntityListener.class)
@NamedQueries({
        @NamedQuery(name = UserEntity.SELECT_BY_LAST_NAME, query = "SELECT e FROM UserEntity e WHERE e.lastName = :lastName") })
public class UserEntity extends BaseUserEntity {

    private static final long serialVersionUID = -1548565565852076272L;

    static final String SELECT_BY_LAST_NAME = "UserEntity.selectByLastName";

    @Override
    @NotNull
    public String getUserId() {
        return super.getUserId();
    }

    @Override
    @NotNull
    public String getPassword() {
        return super.getPassword();
    }

    public GenderCd getGenderCd() {
        return CodeUtils.decode(getGender(), GenderCd.class);
    }

    public void setGenderCd(GenderCd gender) {
        setGender(gender.getValue());
    }

}

src/main/java/a/b/c/presentation/UserInputController.java
package a.b.c.presentation;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import a.b.c.application.user.UserService;
import a.b.c.domain.code.GenderCd;
import a.b.c.domain.user.UserEntity;
import a.b.c.infrastructure.entitycrud.EntityInputController;

@Named
@ViewScoped
public class UserInputController extends EntityInputController<UserEntity, String, UserService>
        implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * ユーザーID
     */
    private String userId;

    @Inject
    transient UserService service;

    public GenderCd[] get性別() {
        return GenderCd.values();
    }

    @Override
    protected UserService getService() {
        return service;
    }

    @Override
    protected String getEntityId() {
        return getUserId();
    }

    /**
     * ユーザーIDを返却する。
     * 
     * @return ユーザーID
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * ユーザーIDを設定する。
     * 
     * @param userId
     *            ユーザーID
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}

src/main/java/a/b/c/presentation/UserListController.java
package a.b.c.presentation;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import a.b.c.application.user.UserService;
import a.b.c.domain.user.UserEntity;
import a.b.c.infrastructure.entitycrud.EntityListController;

@Named
@RequestScoped
public class UserListController extends EntityListController<UserEntity, String, UserService> {

    @Inject
    UserService service;

    @Override
    protected UserService getService() {
        return service;
    }
}

src/main/webapp/pages/management/user-input.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:cmp="http://java.sun.com/jsf/composite/cmp" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

<ui:composition template="/WEB-INF/templates/input-template.xhtml">
  <ui:param name="inputController" value="#{userInputController}" />

  <ui:define name="title">ユーザー登録</ui:define>

  <f:metadata>
    <f:viewParam name="userId" value="#{userInputController.userId}" />
    <f:viewAction action="#{userInputController.init}" />
  </f:metadata>

  <ui:define name="inputForm">

    <cmp:inputText id="userId" label="ユーザーID" value="#{userInputController.entity.userId}" />
    <cmp:inputSecret id="password" label="パスワード" value="#{userInputController.entity.password}"
      redisplay="true" />
    <cmp:inputText id="lastName" label="姓" value="#{userInputController.entity.lastName}" />
    <cmp:inputText id="firstName" label="名" value="#{userInputController.entity.firstName}" />
    <cmp:selectOneRadio id="gender" label="性別" value="#{userInputController.entity.gender}"
      selectItems="#{userInputController.性別}" />

  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/management/user-list.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:cmp="http://java.sun.com/jsf/composite/cmp" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

<ui:composition template="/WEB-INF/templates/form-template.xhtml">
  <ui:define name="title">ユーザーリスト</ui:define>

  <ui:define name="form">

    <cmp:inputText id="userId" label="ユーザー" value="#{userListController.condition.params.lk_userId}" />

    <div class="col-sm-offset-2 col-sm-8">
      <h:commandButton id="search" action="#{userListController.search}" value="検索" immediate="false"
        styleClass="btn btn-default">
        <f:ajax execute="@form" render="@form" />
      </h:commandButton>
      <h:commandButton id="clear" action="#{userListController.clear}" value="クリア" immediate="true"
        styleClass="btn btn-default">
        <f:ajax execute="@form" render="@form" />
      </h:commandButton>
    </div>

    <h:dataTable var="u" value="#{userListController.list}" rendered="#{not empty userListController.list}"
      styleClass="table table-hover">
      <f:facet name="caption">
        <cmp:pagination model="#{userListController}" />
      </f:facet>

      <h:column>
        <f:facet name="header">表示</f:facet>
        <h:link outcome="user-input" value="表示">
          <f:param name="userId" value="#{u.userId}" />
          <f:param name="cid" value="#{javax.enterprise.context.conversation.id}" />
        </h:link>
      </h:column>

      <h:column>
        <f:facet name="header">
          <h:commandLink action="#{userListController.sort('userId')}" value="ユーザーID">
            <f:ajax render="@form" />
          </h:commandLink>
        </f:facet>
        <h:outputText id="user-userId" value="#{u.userId}" styleClass="user-userId ">
        </h:outputText>
      </h:column>

      <h:column>
        <f:facet name="header">
          <h:commandLink action="#{userListController.sort('lastName')}" value="姓">
            <f:ajax render="@form" />
          </h:commandLink>
        </f:facet>
        <h:outputText id="user-lastName" value="#{u.lastName}" styleClass="user-lastName ">
        </h:outputText>
      </h:column>

      <h:column>
        <f:facet name="header">
          <h:commandLink action="#{userListController.sort('firstName')}" value="名">
            <f:ajax render="@form" />
          </h:commandLink>
        </f:facet>
        <h:outputText id="user-firstName" value="#{u.firstName}" styleClass="user-firstName ">
        </h:outputText>
      </h:column>

      <h:column>
        <f:facet name="header">
          <h:commandLink action="#{userListController.sort('gender')}" value="性別">
            <f:ajax render="@form" />
          </h:commandLink>
        </f:facet>
        <h:outputText id="user-gender" value="#{u.genderCd}" styleClass="user-gender ">
        </h:outputText>
      </h:column>

    </h:dataTable>

  </ui:define>
</ui:composition>
</html>